name: 'sarif-orchestrator-action'
description: 'Adaptation of sarif-orchestrator to a GitHub Action'
inputs:
  config-dir:
    description: 'Configuration directory'
    required: true
  config-file:
    description: 'Run file'
    required: true
  type-reporting:
    description: 'Type of reporting'
    required: true
  pat:
    description: 'Personal Access Token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: barroqueiro/sarif-orchestrator
        token: ${{ inputs.pat }}
    - run: mkdir /tmp/input /tmp/output /tmp/output/Reporting /tmp/output/Reports
      shell: bash
    - run: echo "CONFIG_FILE=${{ inputs.config-file }}" >> .env
      shell: bash
    - run: echo "TYPE=${{ inputs.type-reporting }}" >> .env
      shell: bash
    - run: echo "CONFIG_HOST_DIR=${{ inputs.config_dir }}" >> .env
      shell: bash
    - run: cp .env ./docker
      shell: bash
    - run: cd sarif-orchestrator/docker
      shell: bash
    - run: cat .env
      shell: bash
    # - id: build image
    #   run: docker-compose build
    #   shell: bash
    # - run: docker-compose up orchestrator
    #   shell: bash
    # - run: docker-compose up report
    #   shell: bash