name: 'sarif-orchestrator-action'
description: 'Adaptation of sarif-orchestrator to a GitHub Action'
inputs:
  config-dir:
    description: 'Configuration directory'
    required: true
  config-file:
    description: 'Run file'
    required: true
  type-reporting:
    description: 'Type of reporting'
    required: true
  pat:
    description: 'Personal Access Token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: barroqueiro/sarif-orchestrator
        token: ${{ inputs.pat }}
    - run: ls -la ..
    - run: |
          mkdir /tmp/input /tmp/output /tmp/output/Reporting /tmp/output/Reports
          cd docker
          touch .env
          echo "INPUT_HOST_DIR=/tmp/input" >> .env
          echo "OUTPUT_HOST_DIR=/tmp/output" >> .env
          echo "INPUT_DIR=/tmp/output/Reporting" >> .env
          echo "OUTPUT_DIR=/tmp/output/Reports" >> .env
          echo "CONFIG_FILE=${{ inputs.config-file }}" >> .env
          echo "TYPE=${{ inputs.type-reporting }}" >> .env
          echo "CONFIG_HOST_DIR=${{ inputs.config-dir }}" >> .env
          cat .env
      shell: bash

          # docker-compose build
          # docker-compose up orchestrator
          # docker-compose up report